### ISSUE TITLE
Travis: Linuxbrew failing to build glibc

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew-emacs#413]
The Linux runs on Travis have been failing when it has to build glibc: https://travis-ci.org/Homebrew/homebrew-emacs/jobs/155672549

cc @rwhogg any ideas?

**Comment by dunn** [comment]
Looks similar to https://github.com/Linuxbrew/homebrew-core/pull/231#issuecomment-218196153; @sjackman what was the problem in that case?

**Comment by rwhogg** [comment]
[This thread](https://github.com/uzh-rpg/rpg_svo/issues/7#issuecomment-44868586) seems to suggest that using the CFLAG `-march=native` with an old GCC (4.6 in both their case and ours) on a new processor (a Haswell in our case) can cause these sorts of errors because the compiler doesn't recognize what the CPU's actually capable of.

**Comment by dunn** [comment]
OK looks like we can fix it with something like this: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

I'm not sure if we should be setting the CXX variable for the entire build or not, though.

**Comment by rwhogg** [comment]
Yeah, that should probably work.

However, you might also want to just set the Linuxbrew installation directory to `/home/linuxbrew/.linuxbrew`. At the expense of some extra verbosity in the Travis file, you'll be able to use a bottle for everything we've bottled - including the vast majority of the X.Org stuff, which should really speed up your builds.

We [recently discovered](https://github.com/Linuxbrew/homebrew-core/issues/825) that Emacs defaults to building with X11, even if `--without-x11` is specified, so you'll probably be building X11 on every single build.

The steps to do that are at https://github.com/Linuxbrew/homebrew-core/blob/master/.travis.yml#L16-L22. I'm happy to help set it up next week if you'd like, but not this week, since I'm taking a holiday from Homebrew to focus on personal stuff.

**Comment by dunn** [comment]
Ah, that's good to know, thanks! I'll try to take a crack at it during the week.

**Comment by rwhogg** [comment]
> We recently discovered that Emacs defaults to building with X11, even if --without-x11 is specified, so you'll probably be building X11 on every single build.

My mistake: https://github.com/Homebrew/homebrew-core/pull/3531 removed X11 support and added a hardcoded `--without-x` into the formula. It will still install `linuxbrew/xorg/xorg` on every single build, but only because it's now a recommended dependency of `cairo` (which in turn comes in through the dependency on `librsvg`). It won't attempt to link to it.

**Comment by dunn** [comment]
There's also this, which I'm not sure the cause of: https://travis-ci.org/Homebrew/homebrew-emacs/builds/156804249#L2205

**Comment by rwhogg** [comment]
> There's also this, which I'm not sure the cause of: https://travis-ci.org/Homebrew/homebrew-emacs/builds/156804249#L2205

Probably fixed by https://github.com/Homebrew/homebrew-emacs/commit/9102968dbbf0abba541cc18266fe8922a03ae7a4

**Comment by dunn** [comment]
Haha, hope so!
